// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olbpttbkxbzrvdabpwjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sYnB0dGJreGJ6cnZkYWJwd2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzQyMjAsImV4cCI6MjA1NzkxMDIyMH0.yTeIUoeBqDxUBw8Bok3xG6pDyE_n0rTjHAyHe-As-uE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);